spring:
  output:
    ansi:
      enabled: always

logging:
  level:
    demo: DEBUG
    ROOT: INFO
  pattern:
    console: "[%clr(%4p)] [%clr(%d{ISO8601}){blue}] [demo-service,%X{traceId:-},%X{spanId:-},%X{client_id:-}] [%clr(%t){magenta}] %clr(%c{1}){cyan}: %m%n"
